### ISSUE TITLE
Trying to store helix in object in a function, but plotHelix keeps saying "object not found"

### ISSUE THREAD

**Issue by stupornova33** [Ikarto/R4RNA#1]
This only happens when my code is in a function, otherwise it works fine. In one of my scripts I was able to print the helix to a file and then read that file directly in the plotHelix function, but it's not working in my other script. Here is the one that is working:

 helix_plot <- ggplotify::as.grob(~R4RNA::plotHelix(helix = R4RNA::readHelix("helix.txt"), line = TRUE, arrow = FALSE))

and here is the one that's not: 
cur_file <- paste0(prefix, "_helix.txt")
helix_plot <- ggplotify::as.grob(~R4RNA::plotHelix(helix = R4RNA::readHelix(cur_file), line = TRUE, arrow = FALSE))
This gives the error "cur_file" not found. The file exists and has no problem being read when the code is not in a function. 

I figured out that the issue with the first one was that the full helix object wasn't being stored, it was missing the # 1234 line at the top, but I am currently at a loss on the second issue.

**Comment by Ikarto** [comment]
Thank you for your appeal. 
May you provide the content of the helix file?
In general, first line in helix file "# 1234"  stands  for the length of the transcript.

**Comment by stupornova33** [comment]
Hi, here is the helix file. I am not sure it is a problem with R4RNA, as I am having a similar problem with an RRNA function. Note that the 67 actually says # 67

# 67      
i	j	length	value
3	63	1	NA
4	62	1	NA
5	61	1	NA
6	60	1	NA
7	59	1	NA
8	57	1	NA
9	56	1	NA
10	55	1	NA
11	54	1	NA
12	51	1	NA
13	50	1	NA
14	49	1	NA
15	48	1	NA
16	47	1	NA
18	45	1	NA
19	44	1	NA
20	43	1	NA
21	42	1	NA
22	41	1	NA
23	40	1	NA

**Comment by Ikarto** [comment]
Your helix file looks correct. I can suggest only problem in the path to file. Please check the path to file inside function.

**Comment by stupornova33** [comment]
Thank you, the file path isn't the problem, but I will close the issue.
